version: '3'

services:
  tatar.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  tatar.questionparser:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

